# Generated by Django 4.2.3 on 2023-08-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_posts_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='blog_post',
            new_name='post',
        ),
    ]
