# Generated by Django 4.2.3 on 2023-08-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_blog_post_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
